export const list=[
    {
        "id":1,
        "name": "Button Through Fine ",
        "imageURL": "https://vcdn-sohoa.vnecdn.net/2021/01/21/HP-Elite-Folio-Front-Left-Forw-6107-5267-1611217952.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":2,
        "name": "Button Through Fine ",
        "imageURL": "https://cdn.tgdd.vn/Files/2017/01/19/939425/cach-cai-hinh-nen-may-tinh-khong-bi-mo_1280x720-800-resize.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":3,
        "name": "Button Through Fine ",
        "imageURL": "https://img.websosanh.vn/v10/users/review/images/zb7yqhofsl4sl/1568434178299_8049307.jpg?compress=85",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":4,
        "name": "Button Through Fine ",
        "imageURL": "https://laptopdieplinh.com/uploads/10-laptop-man-hinh-4k-chan-thuc-song-dong-nhat-2020.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":5,
        "name": "Button Through Fine",
        "imageURL": "https://cdn.tgdd.vn/hoi-dap/1318185/cach-de-man-hinh-may-tinh-luon-sang-khong-tat-tren-windows-800x450.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":6,
        "name": "Button Through Fine ",
        "imageURL": "https://img.websosanh.vn/v10/users/review/images/wzaw6do9mt1qr/laptop-4.jpg?compress=85",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":7,
        "name": "Button Through Fine ",
        "imageURL": "https://vcdn-sohoa.vnecdn.net/2021/01/21/HP-Elite-Folio-Front-Left-Forw-6107-5267-1611217952.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
       
    },
    {
        "id":8,
        "name": "Button Through Fine ",
        "imageURL": "https://cdn.tgdd.vn/Files/2017/01/19/939425/cach-cai-hinh-nen-may-tinh-khong-bi-mo_1280x720-800-resize.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":9,
        "name": "Button Through Fine ",
        "imageURL": "https://img.websosanh.vn/v10/users/review/images/zb7yqhofsl4sl/1568434178299_8049307.jpg?compress=85",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
    {
        "id":10,
        "name": "Button Through Fine ",
        "imageURL": "https://laptopdieplinh.com/uploads/10-laptop-man-hinh-4k-chan-thuc-song-dong-nhat-2020.jpg",
        "description": "Nam tempus turpis .",
        "prices": 20000,
        "amount": 1,
    },
]

